"""Routes for resume upload and candidate profiles."""

from fastapi import APIRouter, Depends, File, HTTPException, UploadFile
from sqlalchemy.orm import Session

from app.db import get_db
from app.documents import DocumentError, extract_text
from app.models import Profile
from app.schemas import ProfileUploadResponse

# A router is a mountable group of routes. main.py calls
# app.include_router(profiles.router), which is what makes these paths live.
# The prefix and tags apply to every route defined below; tags become the
# section headings in the Swagger UI at /docs.
router = APIRouter(prefix="/api/profiles", tags=["profiles"])


@router.post("", response_model=ProfileUploadResponse, status_code=201)
def upload_resume(
    file: UploadFile = File(...),
    db: Session = Depends(get_db),
) -> Profile:
    """Accept a resume upload, extract its text, and store it as a profile.

    Returns 201 because this creates a durable resource. The response carries
    the new row's id, which every later milestone needs in order to submit a
    job against this candidate.
    """
    if file.filename is None:
        raise HTTPException(status_code=400, detail="No filename provided")

    content = file.file.read()
    file_name = file.filename

    try:
        raw_text = extract_text(content, file_name)
    except DocumentError as e:
        raise HTTPException(status_code=400, detail=str(e)) from e

    profile = Profile(original_filename=file_name, raw_text=raw_text)

    # add() stages the object; commit() writes it and ends the transaction.
    # get_db owns the session's lifetime but not its semantics -- only this
    # handler knows that "one uploaded resume" is a complete unit of work.
    db.add(profile)
    db.commit()
    # The id and created_at are generated by Postgres, so the in-memory object
    # does not know them until we read them back.
    db.refresh(profile)

    # response_model + from_attributes builds the response by reading
    # attributes off this ORM object, exposing only the declared fields.
    # `characters` is not a column -- see the property on Profile.
    return profile
