/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe. Returns 200 if the process is up and serving.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Create an account and start a session for it.
         *
         *     Registration necessarily reveals whether an address is taken -- there is
         *     no way to both refuse a duplicate and conceal that it exists. Login is
         *     where the disclosure actually matters, and that path stays silent.
         */
        post: operations["register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Exchange credentials for a session cookie.
         */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description End the current session.
         *
         *     Deliberately not requiring `current_user`. Logging out with an already
         *     invalid session is not an error -- it is the state the caller was asking
         *     for, and answering 401 would leave a confused client apparently unable to
         *     log out.
         */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Who the caller is. 401 when nobody.
         *
         *     This is the client's auth state: a query, not something mirrored into
         *     application state that then has to be kept in sync. `no-store` because a
         *     cached identity is how one user is shown another's account.
         */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Profiles
         * @description Every resume this user has uploaded, newest first.
         *
         *     The endpoint that makes an account durable rather than a single session.
         *     Without it a profile was reachable only through an id the client happened
         *     to still be holding, so a page refresh stranded every upload -- the rows
         *     were never lost, there was simply no way left to ask for them.
         *
         *     Ordered by created_at with the id as a tiebreak. Two uploads can share a
         *     timestamp, and an unstable sort makes a list that reshuffles itself
         *     between renders for no reason the user can see.
         */
        get: operations["list_profiles_api_profiles_get"];
        put?: never;
        /**
         * Upload Resume
         * @description Accept a resume upload, store its text, and queue structured extraction.
         *
         *     Text extraction is synchronous -- it is local CPU work measured in
         *     milliseconds. LLM extraction is not: it measured 26s on Gemini and 57s on
         *     a local model, and it used to run right here, holding the request open
         *     the entire time. It is now enqueued instead.
         *
         *     So this returns 201, not 202. A profile really is created and immediately
         *     readable at GET /api/profiles/{id}; only its structured fields arrive
         *     later. `extraction_ok` is false until the worker finishes, and the client
         *     polls that endpoint the same way it polls a job.
         */
        post: operations["upload_resume_api_profiles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/{profile_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Profile
         * @description Fetch one profile. Polled until `extraction_ok` turns true.
         *
         *     Takes `owned_profile` rather than an id plus a lookup, so the ownership
         *     predicate is structural. There is no version of this handler that
         *     accidentally serves someone else's resume, because it never had the
         *     chance to load one.
         */
        get: operations["get_profile_api_profiles__profile_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Profile
         * @description Delete a resume and everything derived from it.
         *
         *     The cascade is declared by the foreign keys rather than performed here:
         *     `ingest_jobs.profile_id` and `url_batches.profile_id` are both ON DELETE
         *     CASCADE, so the work submitted against this resume goes with it. That is
         *     the honest shape -- a job scored against a resume that no longer exists
         *     can be neither re-scored nor explained, and keeping it would leave the
         *     ops dashboard counting work whose subject is gone.
         *
         *     Deleting the *active* resume promotes the newest survivor instead of
         *     leaving the account with none. An account holding three resumes and
         *     driving its feed from zero of them is a state with no honest UI, and its
         *     only exit would be an activate call the client has to know to make.
         *
         *     204 with no body. There is no meaningful representation of a row that was
         *     just removed, and returning the deleted object invites a client to render
         *     it.
         */
        delete: operations["delete_profile_api_profiles__profile_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/{profile_id}/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reextract Profile
         * @description Re-run extraction for a profile whose earlier attempt failed.
         *
         *     Closes the gap where a provider outage left a profile permanently
         *     un-scoreable with no way to retry it. Safe to call on an
         *     already-extracted profile: the task checks and returns early rather than
         *     spending a second API call.
         *
         *     Ownership matters more here than on a read. This endpoint spends an LLM
         *     call, so without the predicate anyone could run up the bill on someone
         *     else's profile ids.
         */
        post: operations["reextract_profile_api_profiles__profile_id__extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/{profile_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Activate Profile
         * @description Make this resume the active one.
         *
         *     The counterpart to upload's deliberate refusal to auto-promote. Uploading
         *     a draft must not silently swap out whatever drives the feed, so promotion
         *     is an explicit act -- and this is where it happens.
         *
         *     Two statements, one transaction, and the order is not negotiable. The
         *     partial unique index `profiles_one_active_per_user` permits exactly one
         *     active row per user and is enforced as each statement runs, so promoting
         *     before demoting collides with the row being replaced. Clearing first
         *     leaves the account momentarily with no active profile; the index allows
         *     that, and no other transaction can observe it.
         */
        post: operations["activate_profile_api_profiles__profile_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description List jobs, newest first. Filterable by profile and status.
         *
         *     Both filters hit indexed columns. This is the query the M10 ops dashboard
         *     is built on -- `?status=dead` is the dead-letter list.
         *
         *     The ownership join is not optional and not a filter the caller supplies.
         *     `?profile_id=` narrows within what this user owns; it cannot widen beyond
         *     it, so passing someone else's id returns an empty list rather than their
         *     jobs. A listing endpoint is the easiest place to leak everything at once,
         *     because one missing predicate returns every row in the table instead of
         *     one.
         */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        /**
         * Submit Job
         * @description Queue a job-posting URL for processing.
         *
         *     Returns **202 Accepted**, not 201. The distinction is the whole point of
         *     this milestone: 201 would promise the work is done and the result is
         *     available at the returned location. 202 promises only that the request
         *     was accepted for processing -- which is exactly the truth, because
         *     fetching an arbitrary URL takes 200ms to 30s, fails often, and cannot
         *     happen inside a request handler.
         *
         *     Submitting the same URL twice for the same profile returns the existing
         *     job rather than creating a duplicate scrape.
         */
        post: operations["submit_job_api_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job
         * @description Current state of one job. This is the endpoint the frontend polls.
         *
         *     Sets `Cache-Control: no-store` because a cached job status is worse than
         *     useless -- a proxy holding a `queued` response for 30 seconds makes the
         *     UI look stuck when the work has already finished.
         *
         *     Ownership is inherited through the profile rather than stored on the job.
         *     A job belongs to whoever owns the resume it was submitted for, so joining
         *     keeps one source of truth; a `user_id` column here could disagree with
         *     `profiles.user_id` and there would be no way to say which was right.
         */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Batches
         * @description This user's batches, newest first.
         *
         *     Scoped by ownership before any caller-supplied parameter is applied, so
         *     there is no argument that widens the result past what this user owns.
         */
        get: operations["list_batches_api_batches_get"];
        put?: never;
        /**
         * Create Batch
         * @description Accept a URL list -- as a file or as pasted text -- and fan it out.
         *
         *     202, not 201: nothing has been fetched. The batch row exists and N jobs
         *     are queued, which is exactly what "accepted for processing" means.
         *
         *     Parsing happens in the handler rather than in a job. It is line splitting
         *     and string normalization over text already in memory -- microseconds,
         *     local CPU, no network -- so pushing it onto a queue would add a round
         *     trip and a second polling state to save nothing. The expensive part is
         *     the N fetches, and those are queued.
         */
        post: operations["create_batch_api_batches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batches/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Batch
         * @description Aggregate progress for one batch. This is what the client polls.
         *
         *     One query for the whole batch. The alternative -- the client polling N
         *     job endpoints -- turns a 500-item progress view into 250 requests per
         *     second at a 2s interval, which would make the progress display the
         *     heaviest thing in the system.
         */
        get: operations["get_batch_api_batches__batch_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Matches
         * @description Matches for one of the caller's profiles, best first.
         *
         *     This is the query `matches_feed_idx` exists for -- `(profile_id,
         *     final_score DESC)` serves both the filter and the ordering, so the
         *     planner never sorts.
         *
         *     Ownership is checked on the *profile* rather than filtered on the
         *     matches. Filtering alone would return an empty list for someone else's
         *     profile, which is a subtly worse answer: it says "this profile has no
         *     matches" where the truth is "this profile is not yours", and a client
         *     cannot tell an empty feed from a forbidden one.
         *
         *     **The filters here are not the ones in `retrieval.FeedFilters`, and the
         *     duplication is deliberate.** Those run at recall time and decide what gets
         *     *scored*; these run at read time and decide what gets *shown*. Collapsing
         *     them would mean re-running a 200-candidate rerank every time somebody
         *     ticked "remote only", which is a scoring job's worth of work on the
         *     request path -- exactly what section 6.9 puts on a queue instead.
         *
         *     **Closed postings are hidden by default rather than deleted from the
         *     feed.** A role filled after it was scored is still a true record of what
         *     was recommended, and `include_closed` keeps it reachable; showing it
         *     unasked would be presenting a dead link as a live opportunity.
         */
        get: operations["list_matches_api_matches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matches/{match_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Match
         * @description One match with its full skill breakdown.
         *
         *     Joined through `profiles` rather than checked afterwards, so a match
         *     belonging to another user is indistinguishable from one that does not
         *     exist -- the row never leaves the database.
         */
        get: operations["get_match_api_matches__match_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matches/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Build Recommendations
         * @description Ask for this profile's feed to be built, if it needs building.
         *
         *     Section 6.9 option 1 -- lazy, with a warm state. The three properties that
         *     make this the chosen strategy over a nightly sweep are all visible here:
         *     the work is queued rather than run on the request path, it happens because
         *     somebody asked rather than on a schedule, and the cost therefore tracks
         *     active users rather than registered ones.
         *
         *     **202 always, never 200 with results.** Building a feed is a recall plus
         *     200 reranks; doing it inline would make the first feed request the slowest
         *     request in the application and hold a worker-equivalent of work open on a
         *     web connection. The client gets an acknowledgement and polls the feed it
         *     was already polling.
         *
         *     **`already_current` is the interesting return.** A feed that was scored
         *     under the current `scorer_version` does not need rebuilding, so a client
         *     that polls this endpoint cannot stampede the queue -- which matters
         *     because the natural client implementation calls it whenever the feed looks
         *     empty, and an empty feed is exactly the state a user stares at.
         */
        post: operations["build_recommendations_api_matches_recommendations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matches/{match_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Feedback
         * @description Record what the caller thought of a recommendation.
         *
         *     Section 8.6's data collection. Nothing reads this yet -- the blend weights
         *     stay hand-set this semester -- and collecting it anyway is the point: a
         *     label cannot be gathered retroactively, so the cost of starting late is
         *     the whole dataset.
         *
         *     **201 with a new row on every call, including a repeat.** The table is
         *     append-only, so marking a posting `interested` and later `applied` records
         *     both, in order. That sequence is the funnel, and it is exactly what a
         *     later ranking model would learn from; an upsert keyed on the match would
         *     quietly discard it.
         *
         *     Ownership joins through `profiles` for the same reason `get_match` does:
         *     a match belonging to somebody else must be indistinguishable from one that
         *     does not exist, or this endpoint becomes a way to enumerate match ids.
         */
        post: operations["submit_feedback_api_matches__match_id__feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Overview
         * @description Everything the dashboard polls, in one round trip.
         *
         *     One endpoint rather than five because the panels are read together and a
         *     dashboard that fires five requests every two seconds is its own load
         *     problem. The cost here is bounded: a handful of Redis reads plus one
         *     grouped SQL count.
         */
        get: operations["overview_api_ops_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/dead-letter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dead Letter
         * @description Jobs that exhausted their retries, newest first.
         *
         *     Sourced from Postgres rather than RQ's FailedJobRegistry because the row
         *     is the durable record: it survives the registry's TTL and carries the
         *     attempt count and the truncated error. The registry is the transport's
         *     view; `ingest_jobs` is ours.
         */
        get: operations["dead_letter_api_ops_dead_letter_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/jobs/{job_id}/requeue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Requeue
         * @description Put a failed job back on its queue.
         *
         *     Resets `attempts` to zero. A requeue is an operator asserting the cause
         *     was fixed, so the job deserves a fresh retry budget rather than
         *     dead-lettering again on its next tick because the counter was already
         *     exhausted.
         */
        post: operations["requeue_api_ops_jobs__job_id__requeue_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BatchCreateResponse
         * @description What POST /api/batches returns once a URL list has been accepted.
         *
         *     Every line the user sent is accounted for: `accepted + rejected +
         *     duplicates` equals the non-blank line count of their file. A batch that
         *     quietly ingests 500 of someone's 4,000 lines is worse than one that
         *     refuses, because they cannot tell which 3,500 are missing.
         */
        BatchCreateResponse: {
            /** Id */
            id: number;
            /** Profile Id */
            profile_id: number;
            /** Filename */
            filename: string;
            /** Accepted */
            accepted: number;
            /** Rejected */
            rejected: number;
            /** Duplicates */
            duplicates: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * BatchStatusResponse
         * @description Aggregate progress for one batch. The endpoint a client polls.
         *
         *     One request covers the whole batch rather than N requests for N jobs --
         *     polling 500 individual job endpoints every two seconds is how a progress
         *     view becomes the heaviest thing in the system.
         *
         *     The counts are derived by grouping jobs on `batch_id`, never read from a
         *     stored counter. See models.UrlBatch for why.
         */
        BatchStatusResponse: {
            /** Id */
            id: number;
            /** Profile Id */
            profile_id: number;
            /** Filename */
            filename: string;
            /** Total */
            total: number;
            /** Rejected */
            rejected: number;
            /** Duplicates */
            duplicates: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Is Complete */
            is_complete: boolean;
        };
        /** Body_create_batch_api_batches_post */
        Body_create_batch_api_batches_post: {
            /** File */
            file?: string | null;
            /** Urls */
            urls?: string | null;
        };
        /** Body_upload_resume_api_profiles_post */
        Body_upload_resume_api_profiles_post: {
            /** File */
            file: string;
        };
        /** DeadLetterItem */
        DeadLetterItem: {
            /** Id */
            id: number;
            /** Url */
            url: string;
            /** Status */
            status: string;
            /** Attempts */
            attempts: number;
            /** Last Error */
            last_error?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ExtractedSkill
         * @description A skill as surfaced to clients -- canonical name plus its evidence.
         */
        ExtractedSkill: {
            /** Name */
            name: string;
            /** Years */
            years?: number | null;
            /** Evidence */
            evidence?: string | null;
            /** Source */
            source?: ("experience" | "project" | "education" | "skills_list" | "unknown") | null;
        };
        /**
         * FeedbackCreate
         * @description A user's judgment on one recommendation.
         *
         *     The verdict is a Literal rather than a plain string so an unknown value is
         *     a 422 naming the alternatives, produced before the request reaches a
         *     handler. The database column is deliberately unconstrained text -- see
         *     `MatchFeedback` -- which puts the vocabulary in exactly one place that can
         *     explain itself to a caller.
         */
        FeedbackCreate: {
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "interested" | "not_interested" | "applied";
        };
        /**
         * FeedbackResponse
         * @description A recorded label.
         *
         *     Returns the row rather than an empty 201 so the client has the id and the
         *     server's `created_at`, which is what orders the funnel. A client that
         *     stamped its own time would be recording clock skew as sequence.
         */
        FeedbackResponse: {
            /** Id */
            id: number;
            /** Match Id */
            match_id: number;
            /** Verdict */
            verdict: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * GateStats
         * @description Content-hash gate effectiveness.
         *
         *     The measurement spec section 6.7 asks to be *reported* rather than
         *     asserted. Counters are process-lifetime and unpartitioned, so this mixes a
         *     board's first crawl -- where every posting is necessarily a miss -- with
         *     the steady-state re-crawls the number is actually about. Read it as a
         *     floor on the gate's value, not as the steady-state rate.
         */
        GateStats: {
            /** Hits */
            hits: number;
            /** Misses */
            misses: number;
            /** Total */
            total: number;
            /** Hit Rate */
            hit_rate: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JobResponse
         * @description A job's current state. This is what the frontend polls.
         */
        JobResponse: {
            /** Id */
            id: number;
            /** Profile Id */
            profile_id: number;
            /** Url */
            url: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed" | "dead";
            /** Attempts */
            attempts: number;
            /** Last Error */
            last_error?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Is Terminal */
            is_terminal: boolean;
        };
        /**
         * JobSubmitRequest
         * @description Body of POST /api/jobs.
         *
         *     `HttpUrl` is doing real work here: a malformed URL is rejected with a
         *     field-level 422 before any row is written or any job enqueued. Without
         *     it, the bad value reaches a worker minutes later and fails there, which
         *     is a far worse place to discover a typo.
         */
        JobSubmitRequest: {
            /**
             * Url
             * Format: uri
             */
            url: string;
            /** Profile Id */
            profile_id: number;
            /** Notes */
            notes?: string | null;
        };
        /**
         * LoginRequest
         * @description Body of POST /api/auth/login.
         *
         *     No length constraints. Validating the shape of a *submitted* password
         *     tells an attacker the policy and rejects legacy passwords that predate a
         *     rule change; the only question at login is whether it matches.
         */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MatchCounts */
        MatchCounts: {
            /** Matched */
            matched: number;
            /** Partial */
            partial: number;
            /** Missing */
            missing: number;
            /** Missing Required */
            missing_required: number;
        };
        /**
         * MatchResponse
         * @description One scored (profile, posting) pair, with the reasoning attached.
         *
         *     Both sub-scores travel with the final one, and the skill breakdown
         *     travels with both. Spec section 8.4 requires it, and the reason is that
         *     a blended number alone is unfalsifiable -- 0.35 says nothing a user can
         *     act on, while "you match 2 of 5 requirements and are short on React
         *     years" does.
         */
        MatchResponse: {
            /** Id */
            id: number;
            /** Profile Id */
            profile_id: number;
            /** Job Posting Id */
            job_posting_id: number;
            /** Semantic Score */
            semantic_score: number;
            /** Skill Score */
            skill_score: number;
            /** Final Score */
            final_score: number;
            /** Origin */
            origin: string;
            /** Scorer Version */
            scorer_version: number;
            /**
             * Scored At
             * Format: date-time
             */
            scored_at: string;
            counts: components["schemas"]["MatchCounts"];
            /** Skills */
            skills: components["schemas"]["MatchSkill"][];
            /** Weights */
            weights: {
                [key: string]: number;
            };
            /** Extraction Failed */
            extraction_failed: boolean;
            /** Posting Url */
            posting_url?: string | null;
            /** Posting Title */
            posting_title?: string | null;
            /** Posting Company */
            posting_company?: string | null;
        };
        /**
         * MatchSkill
         * @description One posting requirement, judged against the candidate.
         *
         *     The unit the UI renders as a green / amber / red row. `bucket` carries
         *     the verdict and `evidence` carries the posting's own words for it, so a
         *     user can see what the score was reacting to rather than being told a
         *     number.
         */
        MatchSkill: {
            /** Name */
            name: string;
            /**
             * Necessity
             * @enum {string}
             */
            necessity: "required" | "preferred" | "unknown";
            /**
             * Bucket
             * @enum {string}
             */
            bucket: "matched" | "partial" | "missing";
            /** Required Years */
            required_years?: number | null;
            /** Candidate Years */
            candidate_years?: number | null;
            /** Evidence */
            evidence?: string | null;
        };
        /**
         * OpsOverview
         * @description Everything the dashboard polls, in one response.
         */
        OpsOverview: {
            /** Queues */
            queues: components["schemas"]["QueueHealth"][];
            /** Workers */
            workers: components["schemas"]["WorkerInfo"][];
            /** Jobs By Status */
            jobs_by_status: components["schemas"]["StatusCount"][];
            /** Job Timeout Seconds */
            job_timeout_seconds: number;
            /** Result Ttl Seconds */
            result_ttl_seconds: number;
            /** Failure Ttl Seconds */
            failure_ttl_seconds: number;
            /** Sources */
            sources: components["schemas"]["SourceFreshness"][];
            gate: components["schemas"]["GateStats"];
        };
        /**
         * ProfileSummary
         * @description One resume in the list of a user's uploads.
         *
         *     Separate from ProfileUploadResponse because of what it leaves out:
         *     `raw_text` and `skills`. A version picker renders a filename, a date, and
         *     a badge -- shipping the full text of every resume a user has ever uploaded
         *     to draw that list is the kind of payload that is fine with three rows and
         *     absurd with thirty.
         *
         *     `characters` survives the cut because it is the one size signal worth
         *     showing, and it is derived from raw_text rather than stored -- see
         *     models.Profile.characters.
         */
        ProfileSummary: {
            /** Id */
            id: number;
            /** Filename */
            filename: string;
            /** Characters */
            characters: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Is Active */
            is_active: boolean;
            /** Extraction Ok */
            extraction_ok: boolean;
            /** Seniority */
            seniority?: ("junior" | "mid" | "senior" | "staff" | "unknown") | null;
            /** Years Experience */
            years_experience?: number | null;
            /** Skill Count */
            skill_count: number;
        };
        /**
         * ProfileUploadResponse
         * @description What POST /api/profiles returns once a resume has been stored.
         *
         *     from_attributes lets FastAPI build this from a SQLAlchemy Profile object
         *     by reading attributes rather than requiring a dict.
         *
         *     `extraction_ok` is deliberately explicit. Text extraction and LLM
         *     extraction fail independently: a resume can parse perfectly and still
         *     come back with no structured profile if the provider was down. Rather
         *     than failing the upload -- which would discard raw_text we successfully
         *     parsed -- the row is saved with null extraction and this flag tells the
         *     client which happened. A client seeing skills=[] otherwise cannot
         *     distinguish "no skills found" from "extraction never ran".
         */
        ProfileUploadResponse: {
            /** Id */
            id: number;
            /** Filename */
            filename: string;
            /** Characters */
            characters: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Extraction Ok */
            extraction_ok: boolean;
            /** Seniority */
            seniority?: ("junior" | "mid" | "senior" | "staff" | "unknown") | null;
            /** Years Experience */
            years_experience?: number | null;
            /**
             * Skills
             * @default []
             */
            skills: components["schemas"]["ExtractedSkill"][];
            /**
             * Is Active
             * @default false
             */
            is_active: boolean;
            /** Raw Text */
            raw_text: string;
        };
        /**
         * QueueHealth
         * @description One queue's depth and the registries around it.
         */
        QueueHealth: {
            /** Name */
            name: string;
            /** Depth */
            depth: number;
            /** Started */
            started: number;
            /** Failed */
            failed: number;
            /** Deferred */
            deferred: number;
            /** Scheduled */
            scheduled: number;
            /** Declared */
            declared: boolean;
            /** Worker Count */
            worker_count: number;
        };
        /**
         * RecommendationRun
         * @description The outcome of asking for a feed to be built.
         *
         *     `status` rather than a bare boolean because the three cases call for three
         *     different things from the UI: `queued` means show a building state and keep
         *     polling, `already_current` means the feed on screen is the answer, and
         *     `profile_not_ready` means wait for extraction rather than for scoring. A
         *     boolean would collapse the last two into "nothing happened", and the user
         *     would be told to wait for a job that is never going to run.
         */
        RecommendationRun: {
            /** Profile Id */
            profile_id: number;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "already_current" | "profile_not_ready";
            /** Queued */
            queued: boolean;
        };
        /**
         * RegisterRequest
         * @description Body of POST /api/auth/register.
         *
         *     `EmailStr` rejects a malformed address with a field-level 422 before any
         *     row is written. The minimum length is deliberately a floor rather than a
         *     composition rule -- no "must contain a symbol", because those rules push
         *     people toward `Password1!` and measurably reduce entropy compared with
         *     simply requiring more characters.
         */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** RequeueResponse */
        RequeueResponse: {
            /** Id */
            id: number;
            /** Status */
            status: string;
            /** Queue */
            queue: string;
        };
        /**
         * SourceFreshness
         * @description How current one board's slice of the catalog is.
         *
         *     `last_success_at` is the honest freshness figure and `last_crawled_at` is
         *     not: a source that has been attempted every hour and succeeded once last
         *     week looks perfectly healthy on the second column alone. Both are exposed
         *     so the gap between them is visible, because that gap *is* the failure --
         *     a crawler that runs on schedule and returns nothing produces a catalog
         *     that ages while every dashboard says it is being tended.
         */
        SourceFreshness: {
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Board Token */
            board_token: string;
            /** Display Name */
            display_name: string;
            /** Enabled */
            enabled: boolean;
            /** Crawl Interval Seconds */
            crawl_interval_seconds: number;
            /** Last Crawled At */
            last_crawled_at?: string | null;
            /** Last Success At */
            last_success_at?: string | null;
            /** Consecutive Failures */
            consecutive_failures: number;
            /** Circuit Open */
            circuit_open: boolean;
            /** Seconds Since Success */
            seconds_since_success?: number | null;
            /** Is Stale */
            is_stale: boolean;
            /** Open Postings */
            open_postings: number;
        };
        /** StatusCount */
        StatusCount: {
            /** Status */
            status: string;
            /** Count */
            count: number;
        };
        /**
         * UserResponse
         * @description A user as returned to clients. Note what is absent: password_hash.
         *
         *     This is the concrete reason ORM models are not reused as API responses.
         *     Returning a `User` directly would serialize every column it has, and the
         *     first person to notice would be whoever reads the hash out of the
         *     response body.
         */
        UserResponse: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Is Admin
             * @default false
             */
            is_admin: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WorkerInfo
         * @description One RQ worker process and the queues it drains.
         */
        WorkerInfo: {
            /** Name */
            name: string;
            /** State */
            state: string;
            /** Queues */
            queues: string[];
            /** Current Job Id */
            current_job_id?: string | null;
            /** Successful Jobs */
            successful_jobs: number;
            /** Failed Jobs */
            failed_jobs: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    list_profiles_api_profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileSummary"][];
                };
            };
        };
    };
    upload_resume_api_profiles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_resume_api_profiles_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_api_profiles__profile_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_profile_api_profiles__profile_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reextract_profile_api_profiles__profile_id__extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_profile_api_profiles__profile_id__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: {
                profile_id?: number | null;
                status?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_job_api_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobSubmitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_batches_api_batches_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchStatusResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_batch_api_batches_post: {
        parameters: {
            query: {
                profile_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_batch_api_batches_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_batch_api_batches__batch_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_matches_api_matches_get: {
        parameters: {
            query: {
                profile_id: number;
                limit?: number;
                origin?: string | null;
                remote_only?: boolean;
                seniority?: string[] | null;
                max_min_years?: number | null;
                include_closed?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_match_api_matches__match_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    build_recommendations_api_matches_recommendations_post: {
        parameters: {
            query: {
                profile_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_feedback_api_matches__match_id__feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overview_api_ops_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpsOverview"];
                };
            };
        };
    };
    dead_letter_api_ops_dead_letter_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeadLetterItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    requeue_api_ops_jobs__job_id__requeue_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequeueResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
