/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe. Returns 200 if the process is up and serving.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Create an account and start a session for it.
         *
         *     Registration necessarily reveals whether an address is taken -- there is
         *     no way to both refuse a duplicate and conceal that it exists. Login is
         *     where the disclosure actually matters, and that path stays silent.
         */
        post: operations["register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Exchange credentials for a session cookie.
         */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description End the current session.
         *
         *     Deliberately not requiring `current_user`. Logging out with an already
         *     invalid session is not an error -- it is the state the caller was asking
         *     for, and answering 401 would leave a confused client apparently unable to
         *     log out.
         */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Who the caller is. 401 when nobody.
         *
         *     This is the client's auth state: a query, not something mirrored into
         *     application state that then has to be kept in sync. `no-store` because a
         *     cached identity is how one user is shown another's account.
         */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Resume
         * @description Accept a resume upload, store its text, and queue structured extraction.
         *
         *     Text extraction is synchronous -- it is local CPU work measured in
         *     milliseconds. LLM extraction is not: it measured 26s on Gemini and 57s on
         *     a local model, and it used to run right here, holding the request open
         *     the entire time. It is now enqueued instead.
         *
         *     So this returns 201, not 202. A profile really is created and immediately
         *     readable at GET /api/profiles/{id}; only its structured fields arrive
         *     later. `extraction_ok` is false until the worker finishes, and the client
         *     polls that endpoint the same way it polls a job.
         */
        post: operations["upload_resume_api_profiles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/{profile_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Profile
         * @description Fetch one profile. Polled until `extraction_ok` turns true.
         *
         *     Takes `owned_profile` rather than an id plus a lookup, so the ownership
         *     predicate is structural. There is no version of this handler that
         *     accidentally serves someone else's resume, because it never had the
         *     chance to load one.
         */
        get: operations["get_profile_api_profiles__profile_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/{profile_id}/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reextract Profile
         * @description Re-run extraction for a profile whose earlier attempt failed.
         *
         *     Closes the gap where a provider outage left a profile permanently
         *     un-scoreable with no way to retry it. Safe to call on an
         *     already-extracted profile: the task checks and returns early rather than
         *     spending a second API call.
         *
         *     Ownership matters more here than on a read. This endpoint spends an LLM
         *     call, so without the predicate anyone could run up the bill on someone
         *     else's profile ids.
         */
        post: operations["reextract_profile_api_profiles__profile_id__extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description List jobs, newest first. Filterable by profile and status.
         *
         *     Both filters hit indexed columns. This is the query the M10 ops dashboard
         *     is built on -- `?status=dead` is the dead-letter list.
         *
         *     The ownership join is not optional and not a filter the caller supplies.
         *     `?profile_id=` narrows within what this user owns; it cannot widen beyond
         *     it, so passing someone else's id returns an empty list rather than their
         *     jobs. A listing endpoint is the easiest place to leak everything at once,
         *     because one missing predicate returns every row in the table instead of
         *     one.
         */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        /**
         * Submit Job
         * @description Queue a job-posting URL for processing.
         *
         *     Returns **202 Accepted**, not 201. The distinction is the whole point of
         *     this milestone: 201 would promise the work is done and the result is
         *     available at the returned location. 202 promises only that the request
         *     was accepted for processing -- which is exactly the truth, because
         *     fetching an arbitrary URL takes 200ms to 30s, fails often, and cannot
         *     happen inside a request handler.
         *
         *     Submitting the same URL twice for the same profile returns the existing
         *     job rather than creating a duplicate scrape.
         */
        post: operations["submit_job_api_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job
         * @description Current state of one job. This is the endpoint the frontend polls.
         *
         *     Sets `Cache-Control: no-store` because a cached job status is worse than
         *     useless -- a proxy holding a `queued` response for 30 seconds makes the
         *     UI look stuck when the work has already finished.
         *
         *     Ownership is inherited through the profile rather than stored on the job.
         *     A job belongs to whoever owns the resume it was submitted for, so joining
         *     keeps one source of truth; a `user_id` column here could disagree with
         *     `profiles.user_id` and there would be no way to say which was right.
         */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Overview
         * @description Everything the dashboard polls, in one round trip.
         *
         *     One endpoint rather than five because the panels are read together and a
         *     dashboard that fires five requests every two seconds is its own load
         *     problem. The cost here is bounded: a handful of Redis reads plus one
         *     grouped SQL count.
         */
        get: operations["overview_api_ops_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/dead-letter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dead Letter
         * @description Jobs that exhausted their retries, newest first.
         *
         *     Sourced from Postgres rather than RQ's FailedJobRegistry because the row
         *     is the durable record: it survives the registry's TTL and carries the
         *     attempt count and the truncated error. The registry is the transport's
         *     view; `ingest_jobs` is ours.
         */
        get: operations["dead_letter_api_ops_dead_letter_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/jobs/{job_id}/requeue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Requeue
         * @description Put a failed job back on its queue.
         *
         *     Resets `attempts` to zero. A requeue is an operator asserting the cause
         *     was fixed, so the job deserves a fresh retry budget rather than
         *     dead-lettering again on its next tick because the counter was already
         *     exhausted.
         */
        post: operations["requeue_api_ops_jobs__job_id__requeue_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_resume_api_profiles_post */
        Body_upload_resume_api_profiles_post: {
            /** File */
            file: string;
        };
        /** DeadLetterItem */
        DeadLetterItem: {
            /** Id */
            id: number;
            /** Url */
            url: string;
            /** Status */
            status: string;
            /** Attempts */
            attempts: number;
            /** Last Error */
            last_error?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ExtractedSkill
         * @description A skill as surfaced to clients -- canonical name plus its evidence.
         */
        ExtractedSkill: {
            /** Name */
            name: string;
            /** Years */
            years?: number | null;
            /** Evidence */
            evidence?: string | null;
            /** Source */
            source?: ("experience" | "project" | "education" | "skills_list" | "unknown") | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JobResponse
         * @description A job's current state. This is what the frontend polls.
         */
        JobResponse: {
            /** Id */
            id: number;
            /** Profile Id */
            profile_id: number;
            /** Url */
            url: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed" | "dead";
            /** Attempts */
            attempts: number;
            /** Last Error */
            last_error?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Is Terminal */
            is_terminal: boolean;
        };
        /**
         * JobSubmitRequest
         * @description Body of POST /api/jobs.
         *
         *     `HttpUrl` is doing real work here: a malformed URL is rejected with a
         *     field-level 422 before any row is written or any job enqueued. Without
         *     it, the bad value reaches a worker minutes later and fails there, which
         *     is a far worse place to discover a typo.
         */
        JobSubmitRequest: {
            /**
             * Url
             * Format: uri
             */
            url: string;
            /** Profile Id */
            profile_id: number;
            /** Notes */
            notes?: string | null;
        };
        /**
         * LoginRequest
         * @description Body of POST /api/auth/login.
         *
         *     No length constraints. Validating the shape of a *submitted* password
         *     tells an attacker the policy and rejects legacy passwords that predate a
         *     rule change; the only question at login is whether it matches.
         */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * OpsOverview
         * @description Everything the dashboard polls, in one response.
         */
        OpsOverview: {
            /** Queues */
            queues: components["schemas"]["QueueHealth"][];
            /** Workers */
            workers: components["schemas"]["WorkerInfo"][];
            /** Jobs By Status */
            jobs_by_status: components["schemas"]["StatusCount"][];
            /** Job Timeout Seconds */
            job_timeout_seconds: number;
            /** Result Ttl Seconds */
            result_ttl_seconds: number;
            /** Failure Ttl Seconds */
            failure_ttl_seconds: number;
        };
        /**
         * ProfileUploadResponse
         * @description What POST /api/profiles returns once a resume has been stored.
         *
         *     from_attributes lets FastAPI build this from a SQLAlchemy Profile object
         *     by reading attributes rather than requiring a dict.
         *
         *     `extraction_ok` is deliberately explicit. Text extraction and LLM
         *     extraction fail independently: a resume can parse perfectly and still
         *     come back with no structured profile if the provider was down. Rather
         *     than failing the upload -- which would discard raw_text we successfully
         *     parsed -- the row is saved with null extraction and this flag tells the
         *     client which happened. A client seeing skills=[] otherwise cannot
         *     distinguish "no skills found" from "extraction never ran".
         */
        ProfileUploadResponse: {
            /** Id */
            id: number;
            /** Filename */
            filename: string;
            /** Characters */
            characters: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Extraction Ok */
            extraction_ok: boolean;
            /** Seniority */
            seniority?: ("junior" | "mid" | "senior" | "staff" | "unknown") | null;
            /** Years Experience */
            years_experience?: number | null;
            /**
             * Skills
             * @default []
             */
            skills: components["schemas"]["ExtractedSkill"][];
            /** Raw Text */
            raw_text: string;
        };
        /**
         * QueueHealth
         * @description One queue's depth and the registries around it.
         */
        QueueHealth: {
            /** Name */
            name: string;
            /** Depth */
            depth: number;
            /** Started */
            started: number;
            /** Failed */
            failed: number;
            /** Deferred */
            deferred: number;
            /** Scheduled */
            scheduled: number;
            /** Declared */
            declared: boolean;
            /** Worker Count */
            worker_count: number;
        };
        /**
         * RegisterRequest
         * @description Body of POST /api/auth/register.
         *
         *     `EmailStr` rejects a malformed address with a field-level 422 before any
         *     row is written. The minimum length is deliberately a floor rather than a
         *     composition rule -- no "must contain a symbol", because those rules push
         *     people toward `Password1!` and measurably reduce entropy compared with
         *     simply requiring more characters.
         */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** RequeueResponse */
        RequeueResponse: {
            /** Id */
            id: number;
            /** Status */
            status: string;
            /** Queue */
            queue: string;
        };
        /** StatusCount */
        StatusCount: {
            /** Status */
            status: string;
            /** Count */
            count: number;
        };
        /**
         * UserResponse
         * @description A user as returned to clients. Note what is absent: password_hash.
         *
         *     This is the concrete reason ORM models are not reused as API responses.
         *     Returning a `User` directly would serialize every column it has, and the
         *     first person to notice would be whoever reads the hash out of the
         *     response body.
         */
        UserResponse: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WorkerInfo
         * @description One RQ worker process and the queues it drains.
         */
        WorkerInfo: {
            /** Name */
            name: string;
            /** State */
            state: string;
            /** Queues */
            queues: string[];
            /** Current Job Id */
            current_job_id?: string | null;
            /** Successful Jobs */
            successful_jobs: number;
            /** Failed Jobs */
            failed_jobs: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    upload_resume_api_profiles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_resume_api_profiles_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_api_profiles__profile_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reextract_profile_api_profiles__profile_id__extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: {
                profile_id?: number | null;
                status?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_job_api_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobSubmitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overview_api_ops_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpsOverview"];
                };
            };
        };
    };
    dead_letter_api_ops_dead_letter_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeadLetterItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    requeue_api_ops_jobs__job_id__requeue_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequeueResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
