"""add extraction_version to profiles

Revision ID: a17c4e9b2d38
Revises: 25e4df2cbdff
Create Date: 2026-08-03 03:14:22.118904

Records which generation of the extraction prompt and schema produced each
profile's `extracted` blob, so a prompt improvement can find the rows it
invalidated. A content hash cannot see a prompt change; without a version
column beside it, better instructions would silently leave every stored
profile on the old behaviour.

Written by hand rather than autogenerated. Autogenerate would have produced
the add_column and nothing else -- it has no way to know that existing rows
hold version 1 output, and defaulting them to the new constant would mark
stale extractions as current, which is the exact error this column exists to
prevent.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a17c4e9b2d38'
down_revision: Union[str, Sequence[str], None] = '25e4df2cbdff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Nullable with no server default: null means "never extracted", which is
    # the same thing `extracted IS NULL` says, and the two are written
    # together so they cannot disagree. A default of 1 would claim every
    # future un-extracted row was produced by version 1.
    op.add_column(
        'profiles',
        sa.Column('extraction_version', sa.Integer(), nullable=True),
    )

    # Backfill: rows that already have an extraction got it from version 1,
    # before per-skill `years` inference was added to the prompt. Stamping
    # them accordingly is what makes them show up in
    #
    #     WHERE extraction_version < CURRENT_EXTRACTION_VERSION
    #
    # so they can be re-extracted deliberately. Left null they would be
    # indistinguishable from profiles the LLM never ran on.
    op.execute(
        """
        UPDATE profiles
           SET extraction_version = 1
         WHERE extracted IS NOT NULL
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('profiles', 'extraction_version')
