"""Add pgvector embeddings and the matches table

Revision ID: a4f8c2e17b90
Revises: e7a3c1f9b204
Create Date: 2026-08-03

M7. Three things that have to arrive together, because a match row is
meaningless without somewhere to read both embeddings from.

Hand-written rather than autogenerated. Autogenerate cannot emit
`CREATE EXTENSION` -- it diffs tables, and the extension is a prerequisite
for the column types below rather than a table. Running the autogenerated
version against a database without pgvector fails on the first `vector(384)`
with "type does not exist", which reads as a broken migration rather than a
missing extension.

**Why the dimension is written into the column.** `vector(384)` is not a hint;
Postgres enforces it, and an index over the column is built for that width.
Changing embedding model later means rewriting every row and rebuilding the
index -- which is exactly why spec section 8.2 says choose the model before
this migration exists, and why the choice (all-MiniLM-L6-v2, local, 384) is
recorded in app/embeddings.py rather than left implicit.
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

revision = "a4f8c2e17b90"
down_revision = "e7a3c1f9b204"
branch_labels = None
depends_on = None

EMBEDDING_DIM = 384


def upgrade() -> None:
    # The image is pgvector/pgvector:pg16, so the extension is compiled in and
    # available -- but "available" is not "enabled". This is the statement
    # that enables it, and it belongs in a migration rather than in a manual
    # psql step so that a fresh clone gets a working database from
    # `alembic upgrade head` alone.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # Nullable, no default, no backfill. Every existing row genuinely has no
    # embedding, and NULL says exactly that -- the same reasoning as
    # extraction_version. A zero vector would be worse than useless: it is a
    # valid value that sits at cosine distance 1.0 from everything, so it
    # would look scored and rank last forever.
    #
    # Adding a nullable column with no default is a catalog write, so this is
    # instant regardless of table size.
    op.add_column("profiles", sa.Column("embedding", Vector(EMBEDDING_DIM), nullable=True))
    op.add_column(
        "job_postings", sa.Column("embedding", Vector(EMBEDDING_DIM), nullable=True)
    )

    op.create_table(
        "matches",
        sa.Column("id", sa.BigInteger(), primary_key=True),
        sa.Column(
            "profile_id",
            sa.BigInteger(),
            sa.ForeignKey("profiles.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "job_posting_id",
            sa.BigInteger(),
            sa.ForeignKey("job_postings.id", ondelete="CASCADE"),
            nullable=False,
        ),
        # Scores are NOT NULL. A match row exists because scoring ran; a row
        # with a null score would be a half-written record that every consumer
        # then has to defend against, and there is no state this system can be
        # in where one score is known and another is not.
        # REAL, not sa.Float() -- which maps to double precision on Postgres.
        # These are similarity scores in [0, 1] produced by a model whose own
        # arithmetic is float32, so the extra four bytes per column store
        # nothing but noise, three times over, on the table that grows as
        # profiles x postings.
        sa.Column("semantic_score", postgresql.REAL(), nullable=False),
        sa.Column("skill_score", postgresql.REAL(), nullable=False),
        sa.Column("final_score", postgresql.REAL(), nullable=False),
        # The accounting behind final_score. NOT NULL for the same reason:
        # spec section 8.4 requires the breakdown to be surfaceable, and a
        # nullable column makes that a maybe.
        sa.Column("breakdown", postgresql.JSONB(), nullable=False),
        sa.Column("origin", sa.Text(), nullable=False),
        sa.Column("scorer_version", sa.Integer(), nullable=False),
        sa.Column(
            "scored_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )

    # One row per pair. Re-scoring updates in place; an append-only history
    # would put the same posting in a feed twice at two different ranks the
    # first time anything re-scored.
    op.create_index(
        "matches_profile_posting_uniq",
        "matches",
        ["profile_id", "job_posting_id"],
        unique=True,
    )

    # The feed query verbatim: one profile's matches, best first. Composite in
    # this order so the same index serves the filter and the ordering and the
    # planner never has to sort. DESC is written out because a plain ascending
    # index would still be usable but backwards -- Postgres can scan it in
    # reverse, and the explicit form documents which direction the query
    # actually wants.
    op.execute(
        "CREATE INDEX matches_feed_idx ON matches (profile_id, final_score DESC)"
    )

    # Indexed by hand. Postgres indexes primary keys automatically and foreign
    # keys not at all, so "every match for this posting" -- which is how a
    # posting closing at M8 finds the feeds it has to leave -- would otherwise
    # be a sequential scan over the fastest-growing table here.
    op.create_index("ix_matches_job_posting_id", "matches", ["job_posting_id"])


def downgrade() -> None:
    op.drop_index("ix_matches_job_posting_id", table_name="matches")
    op.execute("DROP INDEX IF EXISTS matches_feed_idx")
    op.drop_index("matches_profile_posting_uniq", table_name="matches")
    op.drop_table("matches")

    op.drop_column("job_postings", "embedding")
    op.drop_column("profiles", "embedding")

    # The extension is deliberately NOT dropped. It is a database-level object
    # that another table could depend on, and dropping it on a downgrade would
    # take those with it. Leaving it costs nothing -- an enabled extension with
    # no columns using it is inert.
