"""add is_admin to users

Revision ID: e7a3c1f9b204
Revises: f2c9a30be584
Create Date: 2026-08-03 05:52:00.000000

Splits "signed in" from "allowed to read system-wide state". Until now the
ops endpoints were gated on `current_user`, so any account that could
register could read queue depth, worker names, job ids, and the error
strings attached to other people's submissions.

Written by hand rather than autogenerated so the backfill is explicit.
Autogenerate would emit the add_column and stop, leaving existing rows to
take the server default -- correct here, but only because the default is the
*restrictive* value. Worth stating rather than inheriting by luck: had this
column been `is_active`, the same shortcut would have silently disabled
every existing account.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e7a3c1f9b204"
down_revision: Union[str, Sequence[str], None] = "f2c9a30be584"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default rather than a Python-side default, so rows inserted by a
    # migration, by psql, or by a future code path that bypasses the ORM all
    # get false. A default living only in the application is a default that is
    # absent exactly when someone goes around the application.
    #
    # NOT NULL is safe to apply in the same statement because the default
    # fills existing rows as the column is added. On a large table this is
    # where you would worry about a rewrite; `users` is small.
    op.add_column(
        "users",
        sa.Column(
            "is_admin",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )

    # No admin is seeded here, deliberately. Doing so would mean either
    # inventing credentials inside a migration -- which then exist in every
    # environment that runs it, production included -- or guessing at an
    # email that may not exist. Promotion is a deliberate act:
    #
    #     UPDATE users SET is_admin = true WHERE email = 'you@example.com';


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("users", "is_admin")
